# Generated by Django 3.1.5 on 2025-02-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='attached_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
