# Generated by Django 3.1.5 on 2025-02-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('hr2', '0003_auto_20250204_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='first_recieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_first_recieved_by', to='hr2.employee'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='first_recieved_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_first_recieved_designation', to='globals.designation'),
        ),
    ]
