# Generated by Django 3.1.5 on 2025-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0004_auto_20250213_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='AcademicResponsibility_designation',
            field=models.TextField(default='Assisttant professor'),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AdministrativeResponsibility_designation',
            field=models.TextField(default='Assisttant professor'),
        ),
    ]
