# Generated by Django 3.1.5 on 2025-03-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0005_auto_20250310_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='personalfileNo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
