# Generated by Django 3.1.5 on 2025-03-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('hr2', '0006_auto_20250310_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='AcademicResponsibility_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_academic_responsibility_designation', to='globals.designation'),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='AdministrativeResponsibility_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_administrative_responsibility_designation', to='globals.designation'),
        ),
    ]
