# Generated by Django 3.1.5 on 2025-03-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0008_leaveform_attached_pdf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='AcademicResponsibility_accepted',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='AdministrativeResponsibility_accepted',
        ),
        migrations.RemoveField(
            model_name='leaveform',
            name='attached_pdf_name',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AcademicResponsibility_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='AdministrativeResponsibility_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
