# Generated by Django 3.1.5 on 2025-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0009_auto_20250311_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='attached_pdf_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
