# Generated by Django 3.1.5 on 2025-03-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('hr2', '0010_leaveform_attached_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='approved_by_designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_approved_by_designation', to='globals.designation'),
        ),
    ]
