# Generated by Django 3.1.5 on 2025-03-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0001_initial'),
        ('hr2', '0011_leaveform_approved_by_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filetracking.file'),
        ),
    ]
