# Generated by Django 3.1.5 on 2025-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0012_leaveform_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
