# Generated by Django 3.1.5 on 2025-03-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0013_auto_20250311_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Other', 'Other')], default='Faculty', max_length=10),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='application_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10),
        ),
    ]
