# Generated by Django 3.1.5 on 2025-04-01 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20241007_2302'),
        ('hr2', '0014_auto_20250324_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='commuted_leave_taken',
            new_name='child_care_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='restricted_holiday_taken',
            new_name='half_pay_leave_taken',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='vacation_leave_taken',
            new_name='leave_encashment_taken',
        ),
        migrations.RemoveField(
            model_name='leaveperyear',
            name='casual_leave_allotted',
        ),
        migrations.RemoveField(
            model_name='leaveperyear',
            name='commuted_leave_allotted',
        ),
        migrations.RemoveField(
            model_name='leaveperyear',
            name='earned_leave_allotted',
        ),
        migrations.RemoveField(
            model_name='leaveperyear',
            name='restricted_holiday_allotted',
        ),
        migrations.RemoveField(
            model_name='leaveperyear',
            name='special_casual_leave_allotted',
        ),
        migrations.RemoveField(
            model_name='leaveperyear',
            name='vacation_leave_allotted',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='maternity_leave_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='paternity_leave_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_childCareLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_halfPayLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_maternityLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='Noof_paternityLeave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='casual_leave',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='child_care_leave',
            field=models.IntegerField(default=730),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='earned_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='half_pay_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='leave_encashment',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='maternity_leave',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='paternity_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='special_casual_leave',
            field=models.IntegerField(default=15),
        ),
        migrations.CreateModel(
            name='LeaveClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_date', models.DateField(default=datetime.date.today)),
                ('leaveStartDate', models.DateField(blank=True, null=True)),
                ('leaveEndDate', models.DateField(blank=True, null=True)),
                ('Noof_CasualLeave', models.IntegerField(default=0)),
                ('Noof_specialCasualLeave', models.IntegerField(default=0)),
                ('Noof_earnedLeave', models.IntegerField(default=0)),
                ('Noof_commutedLeave', models.IntegerField(default=0)),
                ('Noof_restrictedHoliday', models.IntegerField(default=0)),
                ('Noof_vacationLeave', models.IntegerField(default=0)),
                ('Noof_maternityLeave', models.IntegerField(default=0)),
                ('Noof_childCareLeave', models.IntegerField(default=0)),
                ('Noof_paternityLeave', models.IntegerField(default=0)),
                ('Noof_halfPayLeave', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approvedDate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('attached_pdf', models.BinaryField(blank=True, null=True)),
                ('attached_pdf_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('application_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_claim_approved_by', to='hr2.employee')),
                ('approved_by_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_claim_approved_by_designation', to='globals.designation')),
                ('leave_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_claims', to='hr2.leaveform')),
            ],
            options={
                'verbose_name': 'Leave Claim',
                'verbose_name_plural': 'Leave Claims',
            },
        ),
    ]
