# Generated by Django 3.1.5 on 2025-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0015_auto_20250401_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='restricted_holiday_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='restricted_holiday',
            field=models.IntegerField(default=2),
        ),
    ]
